[versions]
agp = "8.13.0"
appcompat = "1.7.1"
fancytoast = "2.0.2"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
permissionx = "1.8.1"
toasty = "1.5.2"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
fancytoast = { module = "io.github.shashank02051997:FancyToast", version.ref = "fancytoast" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
permissionx = { module = "com.guolindev.permissionx:permissionx", version.ref = "permissionx" }
toasty = { module = "com.github.GrenderG:Toasty", version.ref = "toasty" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

